### ISSUE TITLE
openapi.support.ApiClient  Caused by: java.lang.NoSuchFieldError: METHOD_NOT_ALLOWED

### ISSUE THREAD

**Issue by beelzebub2006** [featurehub-io/featurehub-java-sdk#19]
Hello, I get a exception: METHOD_NOT_ALLOWED, I don't konw How to resolve it. Console log is below:
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>io.featurehub.sdk</groupId>
            <artifactId>java-client-jersey</artifactId>
            <version>[2, 3)</version>
        </dependency>
    </dependencies>

Caused by: java.lang.NoSuchFieldError: METHOD_NOT_ALLOWED
	at cd.connect.openapi.support.ApiClient.<clinit>(ApiClient.java:579)
	at io.featurehub.client.jersey.JerseyClient.<init>(JerseyClient.java:73)
	at io.featurehub.client.jersey.JerseyClient.<init>(JerseyClient.java:53)
	at io.featurehub.client.jersey.JerseyFeatureHubClientFactory.lambda$createEdgeService$0(JerseyFeatureHubClientFactory.java:13)
	at io.featurehub.client.ServerEvalFeatureContext.build(ServerEvalFeatureContext.java:43)
	at io.featurehub.client.EdgeFeatureHubConfig.init(EdgeFeatureHubConfig.java:65)

**Comment by rvowles** [comment]
Sorry it took a while to response - I didn't see this until now. This implies the wrong URL is being used for features - without posting the _actual_ url, could you perhaps tell me what url you are using please?

**Comment by rvowles** [comment]
Nice to see that was resolved @beelzebub2006  :-)
